// use actions
export const LOGIN_USER = "LOGIN_USER"
export const LOGOUT_USER = "LOGOUT_USER"
export const UPDATE_USER_INFO = "UPDATE_USER_INFO"


// form actions
export const HANDLE_REGISTER = "HANDLE_REGISTER"
export const HANDLE_POST = "HANDLE_POST"
export const HANDLE_SECTION = "HANDLE_SECTION"
export const HANDLE_FORM_STATUS = "HANDLE_FORM_STATUS"


// app actions
export const SET_PAGE = "SET_PAGE"
export const SET_POSTS = "SET_POSTS"
export const SET_SELECTING_STATUS = "SET_SELECTING_STATUS"
export const RESET_SELECTED_POST = "RESET_SELECTED_POST"
export const APPEND_TO_SELECTED_POST = "APPEND_TO_SELECTED_POST"
export const REMOVE_FROM_SELECTED_POST = "REMOVE_FROM_SELECTED_POST"
export const REMOVE_ALL_FROM_POSTS_LIST = "REMOVE_ALL_FROM_POSTS_LIST"
export const SET_PROGRESSING_SECTIONS = "SET_PROGRESSING_SECTIONS"
export const SET_SECTION_ON_PROGRESS = "SET_SECTION_ON_PROGRESS"
export const SET_POST_ON_PROGRESS = "SET_POST_ON_PROGRESS"
export const HANDLE_FORM_IMAGES = "HANDLE_FORM_IMAGES"
export const EDIT_PROGRESSING_SECTIONS = "EDIT_PROGRESSING_SECTIONS"